# 1. Pre-Processing

## 1.1 Import necessary Library

In [1]:
import pandas as pd
import numpy as np

## 1.2 Load CSV

In [2]:
literacy = pd.read_csv('../data/table17_literacy.csv')
attainment = pd.read_csv('../data/table18_attainment.csv')
attendance= pd.read_csv('../data/table20_attendance.csv')

print("Table 17 shape:", literacy.shape)
print("Table 18 shape:", attainment.shape)
print("Table 20 shape:", attendance.shape)

Table 17 shape: (68625, 15)
Table 18 shape: (68625, 22)
Table 20 shape: (20130, 18)

## 1.2 Inspect the Data

In [3]:
# Print out all column names of all three csv
print(literacy.columns.tolist())
print(attainment.columns.tolist())
print(attendance.columns.tolist())

['prov', 'dist', 'gapa', 'sex', 'agegrp', 'provname', 'dname', 'gapaname', 'sexname', 'agegrpname', 'rowtotal', 'a_readwrite', 'b_readonly', 'c_noreadwrite', 'd_notstd']
['prov', 'dist', 'gapa', 'sex', 'agegrp', 'provname', 'dname', 'gapaname', 'sexname', 'agegrpname', 'rowtotal', 'a_earlyedu', 'b_primary', 'c_lowrsecndry', 'd_upprsecndry', 'e_slc', 'f_inter', 'g_graduat', 'h_pgraduat', 'i_other', 'j_nolevel', 'k_notstd']
['prov', 'dist', 'gapa', 'agegrp', 'provname', 'dname', 'gapaname', 'agegrpname', 'male', 'female', 'attnding_m', 'attnding_f', 'evrattnding_m', 'evrattnding_f', 'nvrattnding_m', 'nvrattnding_f', 'notstd_m', 'notstd_f']

### 1.2.1 Identifying merging columns

literacy and attainment both have column 'sex' with value male=1 and female=2, but attendence have seperate  column for gender(eg. male, female, attnding_m, attnding_f).

Merging all df on common keys ['prov','dist','gapa','sex','agegrp'] will fail because attendance has no 'sex' column to merge on

Fix:
Reshape attendance from wide format to long format.
so instead of multiple columns for gender, we have only one column.

### 1.2.2 Reshaping Attendance from wide to long format

In [4]:
# reshaping 
# combine all male into a new df
attendance_male = attendance[['prov', 'dist', 'gapa', 'agegrp', 'male', 'attnding_m', 'evrattnding_m', 'nvrattnding_m', 'notstd_m']]
print(attendance_male.head())
attendance_female = attendance[['prov', 'dist', 'gapa', 'agegrp', 'female', 'attnding_f', 'evrattnding_f', 'nvrattnding_f', 'notstd_f']]
print(attendance_female.head())

   prov  dist  gapa  agegrp     male  attnding_m  evrattnding_m  \
0     0     0     0       0  4690548     3412049         957974
1     0     0     0       5   299149      253984           1391
2     0     0     0       6   294386      268149           1385
3     0     0     0       7   276257      259350           1549
4     0     0     0       8   313330      294877           2158

   nvrattnding_m  notstd_m
0         315788      4737
1          42049      1725
2          24274       578
3          15055       303
4          16087       208
   prov  dist  gapa  agegrp   female  attnding_f  evrattnding_f  \
0     0     0     0       0  4616990     3159061        1017223
1     0     0     0       5   269216      227631           1319
2     0     0     0       6   268359      243227           1352
3     0     0     0       7   258021      240993           1408
4     0     0     0       8   286398      268028           1959

   nvrattnding_f  notstd_f
0         436208      4498
1          38660      1606
2          23256       524
3          15376       244
4          16208       203

### 1.2.3 Adding a New column named sex

In [5]:
# male and female became rowtotal_20 to keep the total value, a new column is added to preserve the gender data
attendance_male.columns = ['prov', 'dist', 'gapa', 'agegrp', 'rowtotal_20', 'attnding', 'evrattnding', 'nvrattnding', 'notstd_20']
attendance_male['sex'] = 1

attendance_female.columns = ['prov', 'dist', 'gapa', 'agegrp', 'rowtotal_20', 'attnding', 'evrattnding', 'nvrattnding', 'notstd_20']
attendance_female['sex'] = 2

C:\Users\kcpra\AppData\Local\Temp\ipykernel_12340\2669745407.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_male['sex'] = 1
C:\Users\kcpra\AppData\Local\Temp\ipykernel_12340\2669745407.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_female['sex'] = 2

In [6]:
 # check
print(attendance_male.head())
print(attendance_female.head())

   prov  dist  gapa  agegrp  rowtotal_20  attnding  evrattnding  nvrattnding  \
0     0     0     0       0      4690548   3412049       957974       315788
1     0     0     0       5       299149    253984         1391        42049
2     0     0     0       6       294386    268149         1385        24274
3     0     0     0       7       276257    259350         1549        15055
4     0     0     0       8       313330    294877         2158        16087

   notstd_20  sex
0       4737    1
1       1725    1
2        578    1
3        303    1
4        208    1
   prov  dist  gapa  agegrp  rowtotal_20  attnding  evrattnding  nvrattnding  \
0     0     0     0       0      4616990   3159061      1017223       436208
1     0     0     0       5       269216    227631         1319        38660
2     0     0     0       6       268359    243227         1352        23256
3     0     0     0       7       258021    240993         1408        15376
4     0     0     0       8       286398    268028         1959        16208

   notstd_20  sex
0       4498    2
1       1606    2
2        524    2
3        244    2
4        203    2

### 1.2.4 Stack male and female datafrmae as one

In [7]:

attendance_gender=pd.concat([attendance_male,attendance_female],ignore_index=True)
print("Shape of attendance gender", attendance_gender.shape)
attendance_gender

Shape of attendance gender (40260, 10)

,prov,dist,gapa,agegrp,rowtotal_20,attnding,evrattnding,nvrattnding,notstd_20,sex
0,0,0,0,0,4690548,3412049,957974,315788,4737,1
1,0,0,0,5,299149,253984,1391,42049,1725,1
2,0,0,0,6,294386,268149,1385,24274,578,1
3,0,0,0,7,276257,259350,1549,15055,303,1
4,0,0,0,8,313330,294877,2158,16087,208,1
...,...,...,...,...,...,...,...,...,...,...
40255,7,77,99,21,1,0,1,0,0,2
40256,7,77,99,22,3,0,3,0,0,2
40257,7,77,99,23,4,0,4,0,0,2
40258,7,77,99,24,1,0,1,0,0,2
40259,7,77,99,25,1,0,1,0,0,2

## 1.3 Another complication

1. Merging literacy and attendance_gender on common keys
2. Calculating attendance rate(attending/rowtotal), in theory it shoulndnt exceed 1.
3. making a new df called invalid rows which consists rows whose rate is > 1 to identify problem

In [8]:
# Test merge literacy and attendance_gender on common keys
# merging literacy and attendance_gender on common keys
merge_test = pd.merge(literacy, attendance_gender, on=['prov','dist','gapa','sex','agegrp'])
print("Merged shape:", merge_test.shape)

#Calculate attendance rate that should be between 0 and 1
merge_test['attending_rate'] = merge_test['attnding'] / merge_test['rowtotal']
print(merge_test['attending_rate'].describe())

# Isolate rows where the rate is impossible (above 1)
invalid_rows = merge_test[merge_test['attending_rate'] > 1]
print("Number of rows with rate > 1:", invalid_rows.shape[0])
invalid_rows[['prov','dist','gapa','sex','agegrp','agegrpname','rowtotal','attnding']].head(10)

Merged shape: (38430, 20)
count    3.797300e+04
mean              inf
std               NaN
min      0.000000e+00
25%      4.918033e-02
50%      2.304365e-01
75%      7.685714e-01
max               inf
Name: attending_rate, dtype: float64
Number of rows with rate > 1: 2843

     prov  dist  gapa  sex  agegrp agegrpname  rowtotal  attnding
3       0     0     0    1       7    11 Year    246281    259350
24      0     0     0    2       7    11 Year    228735    240993
45      1     0     0    1       7    11 Year     40767     44609
66      1     0     0    2       7    11 Year     38859     42893
86      1     1     0    1       6    10 Year      1062      1202
87      1     1     0    1       7    11 Year      1020      1208
108     1     1     0    2       7    11 Year      1018      1183
127     1     1     1    1       5    09 Year       127       134
128     1     1     1    1       6    10 Year       123       129
129     1     1     1    1       7    11 Year       110       119

In [9]:
print("Literacy agegrp mapping:")
print(literacy[['agegrp','agegrpname']].drop_duplicates().sort_values('agegrp'))

print("\nAttendance (original) agegrp mapping:")
print(attendance[['agegrp','agegrpname']].drop_duplicates().sort_values('agegrp'))
print("\nAttainment agegrp mapping:")
print(attainment[['agegrp','agegrpname']].drop_duplicates().sort_values('agegrp'))

Literacy agegrp mapping:
    agegrp     agegrpname
0        0          Total
1        1        05 Year
2        2        06 Year
3        3        07 Year
4        4        08 Year
5        5        09 Year
6        6        10 Year
7        7        11 Year
8        8        12 Year
9        9        13 Year
10      10        14 Year
11      11        15 Year
12      12  16 - 19 Years
13      13  20 - 24 Years
14      14  25 - 29 Years
15      15  30 - 34 Years
16      16  35 - 39 Years
17      17  40 - 44 Years
18      18  45 - 49 Years
19      19  50 - 54 Years
20      20  55 - 59 Years
21      21  60 - 64 Years
22      22  65 - 69 Years
23      23  70 - 74 Years
24      24      75+ Years

Attendance (original) agegrp mapping:
    agegrp agegrpname
0        0   All Ages
1        5     5 Year
2        6     6 Year
3        7     7 Year
4        8     8 Year
5        9     9 Year
6       10    10 Year
7       11    11 Year
8       12    12 Year
9       13    13 Year
10      14    14 Year
11      15    15 Year
12      16    16 Year
13      17    17 Year
14      18    18 Year
15      19    19 Year
16      20    20 Year
17      21    21 Year
18      22    22 Year
19      23    23 Year
20      24    24 Year
21      25    25 Year

Attainment agegrp mapping:
    agegrp     agegrpname
0        0          Total
1        1        05 Year
2        2        06 Year
3        3        07 Year
4        4        08 Year
5        5        09 Year
6        6        10 Year
7        7        11 Year
8        8        12 Year
9        9        13 Year
10      10        14 Year
11      11        15 Year
12      12  16 - 19 Years
13      13  20 - 24 Years
14      14  25 - 29 Years
15      15  30 - 34 Years
16      16  35 - 39 Years
17      17  40 - 44 Years
18      18  45 - 49 Years
19      19  50 - 54 Years
20      20  55 - 59 Years
21      21  60 - 64 Years
22      22  65 - 69 Years
23      23  70 - 74 Years
24      24      75+ Years


### 1.3.1 Problem Identified

#### 1.3.1.1 agegrp problem
Looking at the invalid rows, agegrp=7 is labeled "11 Year" in literacy. This looks inconsistent compared to waht i initially viewed in csv to check data. code 7 should logically mean "7 years old" if the codes directly matched ages.

To confirm, the full agegrp-to-agegrpname mapping was printed for both literacy and attendance_gender side by side:

literacy: agegrp=1 -> 05 Year, agegrp=7 -> 11 Year
attendance_gender: agegrp=5 -> 5 Year, agegrp=7 ->7 Year
attainment: agegrp=1-> 05 Year, agegrp=7 -> 11 Year

Looking at these value , we can determine that agegrp code  in literacy and attainment is not mapped same as in attendance_gender

Literacy and attainment uses agrgrp=age-4 i.e code 1 -> age 5 and so forth
while attendance_gender use the value as is.

#### 1.3.1.2 agegrp value problem
looking at the output above , in literacy and attainment,one code represent only one age only upto code 11, code 12 represent grouped age instead.
but in attendence_gender there is no grouped age ,and age code only goes upto 25

### 1.3.2 Fixing the 'agegrp'

To fix agegrp so its same in all the csv, just add agegrp with 4 to match the actual age.
make sure the initial age is geater than 1 and less than or equal to 11.

In [10]:
# Keep only single-year age codes (1-11 = ages 5-15), then shift by +4 to match attendance's coding

literacy_fixed = literacy[(literacy['agegrp'] >= 1) & (literacy['agegrp'] <= 11)].copy()
literacy_fixed['agegrp'] = literacy_fixed['agegrp'] + 4

attainment_fixed = attainment[(attainment['agegrp'] >= 1) & (attainment['agegrp'] <= 11)].copy()
attainment_fixed['agegrp'] = attainment_fixed['agegrp'] + 4

print(literacy_fixed[['agegrp','agegrpname']].drop_duplicates().sort_values('agegrp'))
print(attainment_fixed[['agegrp','agegrpname']].drop_duplicates().sort_values('agegrp'))

    agegrp agegrpname
1        5    05 Year
2        6    06 Year
3        7    07 Year
4        8    08 Year
5        9    09 Year
6       10    10 Year
7       11    11 Year
8       12    12 Year
9       13    13 Year
10      14    14 Year
11      15    15 Year
    agegrp agegrpname
1        5    05 Year
2        6    06 Year
3        7    07 Year
4        8    08 Year
5        9    09 Year
6       10    10 Year
7       11    11 Year
8       12    12 Year
9       13    13 Year
10      14    14 Year
11      15    15 Year

In [11]:
# check again
merge_check = pd.merge(literacy_fixed, attendance_gender, on=['prov','dist','gapa','sex','agegrp'])
print("Merged shape:", merge_check.shape)

merge_check['attending_rate'] = merge_check['attnding'] / merge_check['rowtotal']
print(merge_check['attending_rate'].describe())

Merged shape: (20130, 20)
count    19707.000000
mean         0.910093
std          0.092284
min          0.000000
25%          0.874646
50%          0.939394
75%          0.970600
max          1.000000
Name: attending_rate, dtype: float64

# 2. Merge the datframe

Merge all three dataframe on common keys ['prov','dist','gapa','sex','agegrp']
and drop unnecessary columns

In [12]:
# updated merge
df_merged = pd.merge(
    literacy_fixed.rename(columns={'rowtotal': 'rowtotal_17'}),
    attainment_fixed.drop(columns=['provname','dname','gapaname','sexname','agegrpname']).rename(columns={'rowtotal': 'rowtotal_18'}),
    on=['prov','dist','gapa','sex','agegrp']
)

df_final = pd.merge(
    df_merged,
    attendance_gender,
    on=['prov','dist','gapa','sex','agegrp']
)

print("Final merged shape:", df_final.shape)

Final merged shape: (20130, 32)

In [13]:
df_final['attending_rate_check'] = df_final['attnding'] / df_final['rowtotal_20']
print(df_final['attending_rate_check'].describe())

count    19704.000000
mean         0.915969
std          0.087477
min          0.000000
25%          0.888889
50%          0.941860
75%          0.970874
max          1.000000
Name: attending_rate_check, dtype: float64

In [14]:
print(df_final.isnull().sum())

prov                      0
dist                      0
gapa                      0
sex                       0
agegrp                    0
provname                  0
dname                     0
gapaname                  0
sexname                   0
agegrpname                0
rowtotal_17               0
a_readwrite               0
b_readonly                0
c_noreadwrite             0
d_notstd                  0
rowtotal_18               0
a_earlyedu                0
b_primary                 0
c_lowrsecndry             0
d_upprsecndry             0
e_slc                     0
f_inter                   0
g_graduat                 0
h_pgraduat                0
i_other                   0
j_nolevel                 0
k_notstd                  0
rowtotal_20               0
attnding                  0
evrattnding               0
nvrattnding               0
notstd_20                 0
attending_rate_check    426
dtype: int64

# 3. Remove aggegrate and null values

original census data constist of aggegrated data with code 0 for aggegrate , we dont need those

In [15]:
df_clean = df_final[(df_final['gapa'] != 0) & (df_final['sex'] != 0) & (df_final['agegrp'] != 0)].copy()
print("After filtering aggregates:", df_clean.shape)

df_clean = df_clean[(df_clean['rowtotal_17']!=0) & (df_clean['rowtotal_18']!=0) & (df_clean['rowtotal_20']!=0)].copy()
print("After filtering totals:", df_clean.shape)

After filtering aggregates: (18260, 33)
After filtering totals: (17824, 33)

# 4. Feature Engineering
new columns
illiteracy_rate=c_noreadwrite/rowtotal_17
high_illiteracy_risk= 1 if illiteracy_rate> median of illiteracy rate

In [16]:
df_clean['illiteracy_rate']=df_clean['c_noreadwrite']/df_clean['rowtotal_17']
median_illiteracy_rate= df_clean['illiteracy_rate'].median()
df_clean['high_illiteracy_risk']= np.where(df_clean['illiteracy_rate']>median_illiteracy_rate,1,0)

In [17]:
print(df_clean[['illiteracy_rate','high_illiteracy_risk']].describe())
print(df_clean['high_illiteracy_risk'].value_counts())

       illiteracy_rate  high_illiteracy_risk
count     17824.000000          17824.000000
mean          0.049302              0.499776
std           0.073979              0.500014
min           0.000000              0.000000
25%           0.005374              0.000000
50%           0.016260              0.000000
75%           0.065346              1.000000
max           1.000000              1.000000
high_illiteracy_risk
0    8916
1    8908
Name: count, dtype: int64

### more feature engineering
turning counts columns such as [a_earlyedu', 'b_primary', 'c_lowrsecndry', 'd_upprsecndry', 'e_slc', '] from table 18 into rate/ percentage by dividing with rowtotal_18
 note other are not included because no 15 year old wwould have graduated , slc count was included to addreess the minority , but no above level was addressed

In [18]:
print(df_clean['e_slc'].describe())
print((df_clean['e_slc'] > 0).sum())

print(df_clean['f_inter'].describe())
print((df_clean['f_inter'] > 0).sum())

count    17824.000000
mean         2.542920
std         20.261782
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1332.000000
Name: e_slc, dtype: float64
1526
count    17824.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: f_inter, dtype: float64
0

In [19]:
# convert to rate
df_clean['early_edu_rate'] = df_clean['a_earlyedu'] / df_clean['rowtotal_18']
df_clean['primary_rate'] = df_clean['b_primary'] / df_clean['rowtotal_18']
df_clean['secondary_rate'] = (df_clean['c_lowrsecndry'] + df_clean['d_upprsecndry']) / df_clean['rowtotal_18']
df_clean['slc_rate'] = df_clean['e_slc'] / df_clean['rowtotal_18']
df_clean['no_education_rate'] = df_clean['j_nolevel'] / df_clean['rowtotal_18']

print(df_clean[['early_edu_rate','primary_rate','secondary_rate','slc_rate','no_education_rate']].describe())

       early_edu_rate  primary_rate  secondary_rate      slc_rate  \
count    17824.000000  17824.000000    17824.000000  17824.000000
mean         0.151538      0.545181        0.290636      0.006496
std          0.293362      0.368594        0.360848      0.027527
min          0.000000      0.000000        0.000000      0.000000
25%          0.000000      0.153388        0.000000      0.000000
50%          0.007486      0.617932        0.000000      0.000000
75%          0.129796      0.918946        0.665825      0.000000
max          1.000000      1.000000        1.000000      0.800000

       no_education_rate
count       17824.000000
mean            0.001454
std             0.014524
min             0.000000
25%             0.000000
50%             0.000000
75%             0.000000
max             1.000000

## even more feature engineering

this is of table 20
turning count values like attnding, evrattnding, nvrattnding
to rate

In [20]:
df_clean['attending_rate']=df_clean['attnding']/df_clean['rowtotal_20']
df_clean['ever_attending_rate']=df_clean['evrattnding']/df_clean['rowtotal_20']
df_clean['never_attending_rate']=df_clean['nvrattnding']/df_clean['rowtotal_20']

In [21]:
print(df_clean[['attending_rate','ever_attending_rate','never_attending_rate']].describe())

       attending_rate  ever_attending_rate  never_attending_rate
count    17824.000000         17824.000000          17824.000000
mean         0.915364             0.037883              0.045345
std          0.087502             0.057156              0.070011
min          0.000000             0.000000              0.000000
25%          0.887534             0.003788              0.005556
50%          0.941748             0.020464              0.015152
75%          0.971609             0.057161              0.055677
max          1.000000             1.000000              0.800000

# 4. Encoding
explain encoding here
for a typiccal ml model, only data they understand are numbers, prov and dist are nominal categories, encoding them to change them to numericla value

One hot encoding
prov only have 7 unique value so one hot encoding works

In [22]:
# one hot encoding
# use pandad .get_dummies to encode
df_clean=pd.get_dummies(df_clean,columns=['prov'],prefix='prov') # creates new column for each unique value in column and fills it as one

In [23]:
print(df_clean.filter(like='prov').columns.tolist())
df_clean.head()

['provname', 'prov_1', 'prov_2', 'prov_3', 'prov_4', 'prov_5', 'prov_6', 'prov_7']

,dist,gapa,sex,agegrp,provname,dname,gapaname,sexname,agegrpname,rowtotal_17,...,attending_rate,ever_attending_rate,never_attending_rate,prov_1,prov_2,prov_3,prov_4,prov_5,prov_6,prov_7
66,1,1,1,5,Province-1,Taplejung,Phaktanlung Gaunpalika,Male,05 Year,144,...,0.930556,0.000000,0.069444,True,False,False,False,False,False,False
67,1,1,1,6,Province-1,Taplejung,Phaktanlung Gaunpalika,Male,06 Year,132,...,0.977273,0.000000,0.022727,True,False,False,False,False,False,False
68,1,1,1,7,Province-1,Taplejung,Phaktanlung Gaunpalika,Male,07 Year,122,...,0.975410,0.000000,0.024590,True,False,False,False,False,False,False
69,1,1,1,8,Province-1,Taplejung,Phaktanlung Gaunpalika,Male,08 Year,113,...,0.946903,0.000000,0.053097,True,False,False,False,False,False,False
70,1,1,1,9,Province-1,Taplejung,Phaktanlung Gaunpalika,Male,09 Year,127,...,0.960630,0.023622,0.015748,True,False,False,False,False,False,False

# 5. Drop Columns

label/text columns:
provname, dname, gapaname, sexname, agegrpname

raw counts:
c_noreadwrite,a_earlyedu, b_primary, c_lowrsecndry, d_upprsecndry, e_slc,attnding, evrattnding, nvrattnding, notstd_20,f_inter, g_graduat, h_pgraduat, i_other, j_nolevel, k_notstd

encoding problem drop:
dist

In [24]:
# before drop 

print(df_clean.shape)
print(df_clean.columns.tolist())

(17824, 49)
['dist', 'gapa', 'sex', 'agegrp', 'provname', 'dname', 'gapaname', 'sexname', 'agegrpname', 'rowtotal_17', 'a_readwrite', 'b_readonly', 'c_noreadwrite', 'd_notstd', 'rowtotal_18', 'a_earlyedu', 'b_primary', 'c_lowrsecndry', 'd_upprsecndry', 'e_slc', 'f_inter', 'g_graduat', 'h_pgraduat', 'i_other', 'j_nolevel', 'k_notstd', 'rowtotal_20', 'attnding', 'evrattnding', 'nvrattnding', 'notstd_20', 'attending_rate_check', 'illiteracy_rate', 'high_illiteracy_risk', 'early_edu_rate', 'primary_rate', 'secondary_rate', 'slc_rate', 'no_education_rate', 'attending_rate', 'ever_attending_rate', 'never_attending_rate', 'prov_1', 'prov_2', 'prov_3', 'prov_4', 'prov_5', 'prov_6', 'prov_7']

In [25]:
#after drop
df_clean = df_clean.drop(columns=['provname','dname','dist','gapa','gapaname','sexname','agegrpname',
                                    'a_readwrite','b_readonly','d_notstd',
                                    'c_noreadwrite','a_earlyedu','b_primary','c_lowrsecndry','d_upprsecndry','e_slc',
                                    'f_inter','g_graduat','h_pgraduat','i_other','j_nolevel','k_notstd',
                                    'attnding','evrattnding','nvrattnding','notstd_20',
                                    'illiteracy_rate', 'attending_rate_check'])

print(df_clean.shape)
print(df_clean.columns.tolist())

(17824, 21)
['sex', 'agegrp', 'rowtotal_17', 'rowtotal_18', 'rowtotal_20', 'high_illiteracy_risk', 'early_edu_rate', 'primary_rate', 'secondary_rate', 'slc_rate', 'no_education_rate', 'attending_rate', 'ever_attending_rate', 'never_attending_rate', 'prov_1', 'prov_2', 'prov_3', 'prov_4', 'prov_5', 'prov_6', 'prov_7']

In [26]:
# export the cleaned data

df_clean.to_csv('../data/pre-processed_data.csv', index=False)
print('Exported')

Exported