# 1. Pre-Processing

## 1.1 Import necessary Library

In [1]:
import pandas as pd
import numpy as np

## 1.2 Load CSV

In [2]:
literacy = pd.read_csv('../data/table17_literacy.csv')
attainment = pd.read_csv('../data/table18_attainment.csv')
attendance= pd.read_csv('../data/table20_attendance.csv')

print("Table 17 shape:", literacy.shape)
print("Table 18 shape:", attainment.shape)
print("Table 20 shape:", attendance.shape)

Table 17 shape: (68625, 15)
Table 18 shape: (68625, 22)
Table 20 shape: (20130, 18)

## 1.2 Inspect the Data

In [5]:
# Print out all column names of all three csv
print(literacy.columns.tolist())
print(attainment.columns.tolist())
print(attendance.columns.tolist())

['prov', 'dist', 'gapa', 'sex', 'agegrp', 'provname', 'dname', 'gapaname', 'sexname', 'agegrpname', 'rowtotal', 'a_readwrite', 'b_readonly', 'c_noreadwrite', 'd_notstd']
['prov', 'dist', 'gapa', 'sex', 'agegrp', 'provname', 'dname', 'gapaname', 'sexname', 'agegrpname', 'rowtotal', 'a_earlyedu', 'b_primary', 'c_lowrsecndry', 'd_upprsecndry', 'e_slc', 'f_inter', 'g_graduat', 'h_pgraduat', 'i_other', 'j_nolevel', 'k_notstd']
['prov', 'dist', 'gapa', 'agegrp', 'provname', 'dname', 'gapaname', 'agegrpname', 'male', 'female', 'attnding_m', 'attnding_f', 'evrattnding_m', 'evrattnding_f', 'nvrattnding_m', 'nvrattnding_f', 'notstd_m', 'notstd_f']

### 1.2.1 Identifying merging columns

literacy and attainment both have column 'sex' with value male=1 and female=2, but attendence have seperate  column for gender(eg. male, female, attnding_m, attnding_f).

Merging all df on common keys ['prov','dist','gapa','sex','agegrp'] will fail because attendance has no 'sex' column to merge on

Fix:
Reshape attendance from wide format to long format.
so instead of multiple columns for gender, we have only one column.

### 1.2.2 Reshaping Attendance from wide to long format

In [9]:
# reshaping 
# combine all male into a new df
attendance_male = attendance[['prov', 'dist', 'gapa', 'agegrp', 'male', 'attnding_m', 'evrattnding_m', 'nvrattnding_m', 'notstd_m']]
print(attendance_male.head())
attendance_female = attendance[['prov', 'dist', 'gapa', 'agegrp', 'female', 'attnding_f', 'evrattnding_f', 'nvrattnding_f', 'notstd_f']]
print(attendance_female.head())

   prov  dist  gapa  agegrp     male  attnding_m  evrattnding_m  \
0     0     0     0       0  4690548     3412049         957974
1     0     0     0       5   299149      253984           1391
2     0     0     0       6   294386      268149           1385
3     0     0     0       7   276257      259350           1549
4     0     0     0       8   313330      294877           2158

   nvrattnding_m  notstd_m
0         315788      4737
1          42049      1725
2          24274       578
3          15055       303
4          16087       208
   prov  dist  gapa  agegrp   female  attnding_f  evrattnding_f  \
0     0     0     0       0  4616990     3159061        1017223
1     0     0     0       5   269216      227631           1319
2     0     0     0       6   268359      243227           1352
3     0     0     0       7   258021      240993           1408
4     0     0     0       8   286398      268028           1959

   nvrattnding_f  notstd_f
0         436208      4498
1          38660      1606
2          23256       524
3          15376       244
4          16208       203

### 1.2.3 Adding a New column named sex

In [10]:
# male and female became rowtotal_20 to keep the total value, a new column is added to preserve the gender data
attendance_male.columns = ['prov', 'dist', 'gapa', 'agegrp', 'rowtotal_20', 'attnding', 'evrattnding', 'nvrattnding', 'notstd_20']
attendance_male['sex'] = 1

attendance_female.columns = ['prov', 'dist', 'gapa', 'agegrp', 'rowtotal_20', 'attnding', 'evrattnding', 'nvrattnding', 'notstd_20']
attendance_female['sex'] = 2

C:\Users\kcpra\AppData\Local\Temp\ipykernel_4284\2669745407.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_male['sex'] = 1
C:\Users\kcpra\AppData\Local\Temp\ipykernel_4284\2669745407.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_female['sex'] = 2

In [ ]:
 # check
print(attendance_male.head())
print(attendance_female.head())

   prov  dist  gapa  agegrp  rowtotal_20  attnding  evrattnding  nvrattnding  \
0     0     0     0       0      4690548   3412049       957974       315788
1     0     0     0       5       299149    253984         1391        42049
2     0     0     0       6       294386    268149         1385        24274
3     0     0     0       7       276257    259350         1549        15055
4     0     0     0       8       313330    294877         2158        16087

   notstd_20  sex
0       4737    1
1       1725    1
2        578    1
3        303    1
4        208    1
   prov  dist  gapa  agegrp  rowtotal_20  attnding  evrattnding  nvrattnding  \
0     0     0     0       0      4616990   3159061      1017223       436208
1     0     0     0       5       269216    227631         1319        38660
2     0     0     0       6       268359    243227         1352        23256
3     0     0     0       7       258021    240993         1408        15376
4     0     0     0       8       286398    268028         1959        16208

   notstd_20  sex
0       4498    2
1       1606    2
2        524    2
3        244    2
4        203    2

### 1.2.4 Stack male and female datafrmae as one

In [14]:

attendance_gender=pd.concat([attendance_male,attendance_female],ignore_index=True)
print("Shape of attendance gender", attendance_gender.shape)
attendance_gender

Shape of attendance gender (40260, 10)

,prov,dist,gapa,agegrp,rowtotal_20,attnding,evrattnding,nvrattnding,notstd_20,sex
0,0,0,0,0,4690548,3412049,957974,315788,4737,1
1,0,0,0,5,299149,253984,1391,42049,1725,1
2,0,0,0,6,294386,268149,1385,24274,578,1
3,0,0,0,7,276257,259350,1549,15055,303,1
4,0,0,0,8,313330,294877,2158,16087,208,1
...,...,...,...,...,...,...,...,...,...,...
40255,7,77,99,21,1,0,1,0,0,2
40256,7,77,99,22,3,0,3,0,0,2
40257,7,77,99,23,4,0,4,0,0,2
40258,7,77,99,24,1,0,1,0,0,2
40259,7,77,99,25,1,0,1,0,0,2

## 1.3 Another complication

1. Merging literacy and attendance_gender on common keys
2. Calculating attendance rate(attending/rowtotal), in theory it shoulndnt exceed 1.
3. making a new df called invalid rows which consists rows whose rate is > 1 to identify problem

In [ ]:
# Test merge literacy and attendance_gender on common keys
# merging literacy and attendance_gender on common keys
merge_test = pd.merge(literacy, attendance_gender, on=['prov','dist','gapa','sex','agegrp'])
print("Merged shape:", merge_test.shape)

#Calculate attendance rate that should be between 0 and 1
merge_test['attending_rate'] = merge_test['attnding'] / merge_test['rowtotal']
print(merge_test['attending_rate'].describe())

# Isolate rows where the rate is impossible (above 1)
invalid_rows = merge_test[merge_test['attending_rate'] > 1]
print("Number of rows with rate > 1:", invalid_rows.shape[0])
invalid_rows[['prov','dist','gapa','sex','agegrp','agegrpname','rowtotal','attnding']].head(10)

Merged shape: (38430, 20)
count    3.797300e+04
mean              inf
std               NaN
min      0.000000e+00
25%      4.918033e-02
50%      2.304365e-01
75%      7.685714e-01
max               inf
Name: attending_rate, dtype: float64
Number of rows with rate > 1: 2843

     prov  dist  gapa  sex  agegrp agegrpname  rowtotal  attnding
3       0     0     0    1       7    11 Year    246281    259350
24      0     0     0    2       7    11 Year    228735    240993
45      1     0     0    1       7    11 Year     40767     44609
66      1     0     0    2       7    11 Year     38859     42893
86      1     1     0    1       6    10 Year      1062      1202
87      1     1     0    1       7    11 Year      1020      1208
108     1     1     0    2       7    11 Year      1018      1183
127     1     1     1    1       5    09 Year       127       134
128     1     1     1    1       6    10 Year       123       129
129     1     1     1    1       7    11 Year       110       119

In [20]:
print("Literacy agegrp mapping:")
print(literacy[['agegrp','agegrpname']].drop_duplicates().sort_values('agegrp'))

print("\nAttendance (original) agegrp mapping:")
print(attendance[['agegrp','agegrpname']].drop_duplicates().sort_values('agegrp'))

Literacy agegrp mapping:
    agegrp     agegrpname
0        0          Total
1        1        05 Year
2        2        06 Year
3        3        07 Year
4        4        08 Year
5        5        09 Year
6        6        10 Year
7        7        11 Year
8        8        12 Year
9        9        13 Year
10      10        14 Year
11      11        15 Year
12      12  16 - 19 Years
13      13  20 - 24 Years
14      14  25 - 29 Years
15      15  30 - 34 Years
16      16  35 - 39 Years
17      17  40 - 44 Years
18      18  45 - 49 Years
19      19  50 - 54 Years
20      20  55 - 59 Years
21      21  60 - 64 Years
22      22  65 - 69 Years
23      23  70 - 74 Years
24      24      75+ Years

Attendance (original) agegrp mapping:
    agegrp agegrpname
0        0   All Ages
1        5     5 Year
2        6     6 Year
3        7     7 Year
4        8     8 Year
5        9     9 Year
6       10    10 Year
7       11    11 Year
8       12    12 Year
9       13    13 Year
10      14    14 Year
11      15    15 Year
12      16    16 Year
13      17    17 Year
14      18    18 Year
15      19    19 Year
16      20    20 Year
17      21    21 Year
18      22    22 Year
19      23    23 Year
20      24    24 Year
21      25    25 Year